const choice = (instructions, criteria) => ({ type:'choice', instructions, criteria });
const score = (instructions, criteria) => ({ type:'score', instructions, criteria });

export const UNDERSTANDING = Object.freeze({
  seg: choice('Qual é o segmento do negócio que a pessoa está descrevendo?', {
    hamburgueria:'Hamburgueria ou lanchonete: hambúrguer artesanal, smash burger, lanches', pizzaria:'Pizzaria: pizza no forno a lenha, rodízio ou delivery de pizza', restaurante:'Restaurante ou bistrô: almoço, jantar, comida caseira ou cozinha autoral', cafeteria:'Cafeteria ou padaria: café especial, pães, brunch, lanche da tarde', estetica:'Clínica de estética: tratamentos faciais e corporais, harmonização, laser', saude:'Clínica médica ou fisioterapia: consultas, exames, reabilitação', pet:'Pet shop ou veterinária: banho e tosa, ração, cuidados com cães e gatos', consultoria:'Consultoria para empresas (B2B): gestão, processos, vendas, estratégia', advocacia:'Advogado ou escritório de advocacia: trabalhista, família, empresarial', marketing:'Agência de marketing digital, social media, design, tráfego pago', tecnologia:'Tecnologia: software, aplicativos, sistemas, SaaS, suporte de TI', cursos:'Cursos, mentorias ou infoprodutos; reforço escolar e preparatórios', imobiliaria:'Imobiliária ou corretor: compra, venda e aluguel de imóveis', arquitetura:'Arquitetura e design de interiores: projetos de casas e ambientes', outro:'Outro tipo de negócio, que não se encaixa em nenhuma opção acima'
  }),
  pers: choice('Qual personalidade de marca combina com o jeito que a pessoa descreveu o negócio e com o estilo que ela pediu?', { rebelde:'Rebelde e ousada: atitude, rock, irreverente, sem frescura', sofisticada:'Sofisticada e elegante: premium, refinada, requintada, discreta', acolhedora:'Acolhedora e familiar: calorosa, de bairro, próxima e carinhosa', divertida:'Divertida e alegre: bem-humorada, colorida, leve e jovem', natural:'Natural e consciente: saudável, orgânica, sustentável, calma', especialista:'Especialista e confiável: técnica, séria, precisa, profissional', moderna:'Moderna e minimalista: clean, contemporânea, digital, direta', tradicional:'Tradicional e artesanal: clássica, com história, feita à mão', energetica:'Energética e motivadora: intensa, esportiva, desafiadora', delicada:'Delicada e romântica: suave, afetiva, sensível', ludica:'Lúdica e infantil: fofa, criativa, feita para crianças' }),
  pub: choice('Qual é o público principal desse negócio?', { jovens:'Jovens e universitários, de 18 a 30 anos', familias:'Famílias com filhos', casais:'Casais: programa a dois, datas especiais', mulheres:'Mulheres adultas que cuidam de si', homens:'Homens adultos', empresas:'Empresas, gestores e donos de negócio (B2B)', criancas:'Crianças e os pais que decidem por elas', tutores:'Tutores de cães e gatos', premium:'Clientes de alta renda e exigentes', maduros:'Pessoas maduras, 50+ e terceira idade', geral:'Público geral do bairro, de todas as idades' }),
  obj: choice('Qual é o principal objetivo do site e das redes desse negócio?', { vender_online:'Vender pela internet: loja virtual, compra online', delivery:'Receber pedidos de delivery pelo WhatsApp ou aplicativo', agendar:'Fazer as pessoas agendarem horário, consulta ou aula', orcamento:'Receber pedidos de orçamento', leads:'Captar contatos interessados para vender depois', visitar:'Levar pessoas a visitar a loja ou o espaço físico', redes:'Ganhar seguidores e ficar conhecido nas redes sociais' }),
  canal: choice('Por qual canal esse negócio mais vende ou atende os clientes?', { whatsapp:'WhatsApp', instagram:'Instagram e redes sociais', site:'Site ou loja online', apps:'Aplicativos de delivery', telefone:'Telefone', presencial:'Presencial: balcão, loja, consultório ou escritório', linkedin:'LinkedIn ou e-mail, contato com empresas' }),
  preco: score('Qual é a faixa de preço percebida desse negócio?', ['Popular: preço baixo, promoções, o mais barato da região','Acessível: bom custo-benefício','Médio: preço justo por boa qualidade','Alto: premium, acima da média','Luxo: exclusivo, alto padrão, sob medida']),
  mat: score('Há quanto tempo esse negócio existe?', ['Ainda vai abrir ou está começando agora','Aberto há pouco tempo, menos de um ano','Alguns anos de mercado','Consolidado, com muitos clientes fiéis','Tradicional, com décadas de história']),
  dif: choice('Qual diferencial esse negócio deve destacar primeiro, pelo que a pessoa falou?', { qualidade:'Qualidade do produto ou serviço: ingredientes, materiais, capricho', rapidez:'Rapidez: entrega ou atendimento ágil', preco:'Preço justo, promoções, custo-benefício', experiencia:'Experiência: ambiente, clima, vivência marcante', exclusividade:'Exclusividade: sofisticação, algo único e autoral', conveniencia:'Praticidade: fácil de pedir, comprar ou agendar', confianca:'Confiança: credibilidade, avaliações, experiência comprovada', resultado:'Resultado: a transformação ou o benefício que a pessoa sente', comunidade:'Comunidade: relação próxima, pertencimento, bairro' }),
  oferta: choice('Qual oferta de boas-vindas faz sentido para esse negócio (vale para site, carrosséis, e-mail e anúncios)?', { cupom10:'10% de desconto na primeira compra', frete:'Entrega grátis no primeiro pedido', avaliacao:'Primeira avaliação ou consulta gratuita', aula:'Aula experimental grátis', diagnostico:'Diagnóstico ou conversa gratuita de 30 minutos', brinde:'Brinde ou mimo na primeira visita', pacote:'Desconto ao fechar um pacote de sessões ou meses', sobremesa:'Sobremesa ou bebida por conta da casa', nenhuma:'Nenhuma oferta, só um bom atendimento' }),
  emoji: score('Quantos emojis a marca desse negócio deve usar nas legendas, e-mails e anúncios?', ['Nenhum emoji: sóbrio e formal','Poucos emojis, só um ou dois','Emojis moderados','Muitos emojis, bem descontraído'])
});
