// Contrato Jev canônico — grupo marca.
export const MARCA = Object.freeze({
  "paleta": {
    "type": "choice",
    "instructions": "Qual paleta de cores combina com esse negócio e com o clima que a pessoa descreveu? Se ela mudou de ideia no meio da fala, vale o que disse por último.",
    "criteria": {
      "rock": "Rock noturno: Preto, vermelho e branco com cara de rock: atitude, noite, show",
      "terra": "Terracota e mostarda: Terrosos quentes (terracota, mostarda, creme): rústico e artesanal",
      "italiano": "Cantina italiana: Vermelho-tomate, verde-manjericão e creme: cantina italiana, pizza, massas, tradição",
      "nude": "Nude e dourado: Nude, rosé e dourado: delicado, feminino e premium (beleza, estética)",
      "luxo": "Preto e dourado: Preto e dourado: luxo, exclusivo, noturno e sofisticado",
      "vinho": "Vinho e creme: Vinho, creme e dourado discreto: elegante, gastronomia, vinhos, casal",
      "salvia": "Sálvia e madeira: Verde-sálvia, creme e madeira: natural, calmo, orgânico, bem-estar",
      "menta": "Menta fresca: Verde-menta, branco e toque de coral: fresco, leve, saudável, nutrição",
      "tropical": "Tropical: Verde-folha, laranja e rosa: tropical, brasileiro, vibrante, praia e açaí",
      "cafe": "Café e caramelo: Marrom-café, creme e caramelo: aconchegante, cafeteria, padaria",
      "pastel": "Pastel doce: Tons pastel (lilás, pêssego, menta): suave, doce, confeitaria, delicado",
      "candy": "Cores de brinquedo: Cores vivas e alegres (rosa, amarelo, azul): infantil, divertido, lúdico",
      "clinico": "Azul clínico: Azul-claro e branco: limpo, higiênico, saúde, odontologia, clínica",
      "lavanda": "Lavanda calma: Lavanda e cinza-azulado: calma, acolhimento, terapia, psicologia",
      "corporativo": "Azul corporativo: Azul-marinho, branco e azul-claro: confiança, corporativo, B2B, finanças",
      "noite": "Azul-noite e ouro: Azul-noite com dourado: sóbrio, premium, advocacia, finanças, consultoria",
      "floresta": "Verde clássico: Verde-escuro e marfim: tradicional, sóbrio, confiável, clássico",
      "neon": "Grafite neon: Grafite escuro com verde-neon: tecnologia, inovação, games, futurista",
      "criativo": "Roxo criativo: Roxo vibrante e amarelo: criativo, jovem, agência, marketing digital",
      "coral": "Petróleo e coral: Azul-petróleo com coral: moderno, criativo, saúde moderna, jovem",
      "energia": "Laranja energia: Laranja vibrante e preto: energia, esporte, intensidade, academia",
      "amarelo": "Amarelo e preto: Amarelo forte e preto: chamativo, popular, promoções, obras, oficina",
      "pink": "Pink noturno: Pink e preto: ousado, moda, beleza jovem, noite",
      "mediterraneo": "Mediterrâneo: Azul-cobalto, branco e amarelo-limão: fresco, verão, praia, pousada",
      "retro": "Retrô anos 70: Laranja queimado, mostarda e marrom: retrô anos 70, vintage, descolado",
      "mono": "Preto e branco: Preto e branco minimalista: moderno, arquitetura, fotografia, moda conceitual"
    }
  },
  "fonte": {
    "type": "choice",
    "instructions": "Qual par de fontes combina com a marca desse negócio?",
    "criteria": {
      "didone": "Didone de revista: Serifa didone de alto contraste, tipo revista de moda + sans fina: luxo, sofisticação, estética premium, casamento",
      "editorial": "Serifa editorial: Serifa editorial moderna com itálico charmoso + sans limpa: elegante e contemporâneo, cozinha autoral, arquitetura",
      "poster": "Pôster condensado: Condensada pesada em caixa alta, estilo pôster de show: rock, esporte, energia, promoções",
      "geometrica": "Geométrica moderna: Geométrica moderna e limpa: tecnologia, startups, arquitetura, marcas contemporâneas",
      "tecnica": "Grotesca técnica: Grotesca técnica com detalhes monoespaçados: tecnologia, dados, software, agências digitais",
      "humanista": "Humanista acolhedora: Humanista suave e acolhedora: saúde, clínicas, psicologia, educação, famílias",
      "arredondada": "Arredondada fofa: Arredondada e fofa, com cara de brinquedo: infantil, pet, doces, divertido",
      "script": "Cursiva artesanal: Letra cursiva feita à mão + serifa calorosa: confeitaria, café, artesanal, afetivo, romântico",
      "slab": "Slab de letreiro: Slab serif robusta de letreiro: oficina, construção, cervejaria, churrasco, rústico",
      "vintage": "Letreiro vintage: Letreiro vintage em versalete largo + máquina de escrever: barbearia clássica, tradição, retrô",
      "classica": "Serifa clássica: Serifa clássica de livro: tradição, confiança, advocacia, contabilidade, consultórios",
      "spa": "Sensorial leve: Sans de contraste suave, leve e sensorial: spa, cosméticos naturais, bem-estar, yoga",
      "grotesca": "Grotesca suíça: Grotesca neutra estilo suíço, forte e direta: corporativo, consultoria, B2B, imobiliária",
      "brutalista": "Mono brutalista: Monoespaçada crua estilo brutalista, com grade aparente: estúdio criativo, moda urbana, galeria, tecnologia com atitude",
      "retro": "Retrô anos 70: Display retrô arredondada, cara de letreiro anos 70: lanchonete, sorveteria, surf, games, diversão nostálgica",
      "artistica": "Expressiva artística: Sans expressiva, larga e ousada: estúdio de design, arquitetura autoral, moda conceitual, galeria, marca jovem e artística",
      "manuscrita": "Letra de mão casual: Letra de mão casual, cara de bilhete: café de bairro, papelaria, aulas particulares, marca afetiva e descontraída"
    }
  },
  "icone": {
    "type": "choice",
    "instructions": "Qual ícone deve estar no logo desse negócio?",
    "criteria": {
      "burger": "Hambúrguer: hambúrguer, lanche, hamburgueria",
      "pizza": "Pizza: fatia de pizza, pizzaria, comida italiana",
      "cafe": "Xícara de café: xícara de café quente, cafeteria, padaria",
      "cupcake": "Cupcake: cupcake, bolo, doces, confeitaria",
      "talheres": "Garfo e faca: garfo e faca, restaurante, refeição",
      "cloche": "Prato servido: prato com tampa (cloche), restaurante sofisticado, buffet",
      "chef": "Chapéu de chef: chapéu de chef, cozinha, gastronomia",
      "tigela": "Tigela: tigela de comida saudável, açaí, salada, poke",
      "taca": "Taça de vinho: taça de vinho, jantar romântico, bar sofisticado",
      "caneca": "Caneca de chope: caneca de chope ou cerveja, bar, cervejaria",
      "sorvete": "Sorvete: casquinha de sorvete, sorveteria, sobremesa",
      "trigo": "Trigo: espiga de trigo, pão artesanal, padaria, natural",
      "chama": "Chama: chama de fogo, brasa, churrasco, paixão, energia",
      "folha": "Folha: folha verde, natural, orgânico, saudável, sustentável",
      "muda": "Broto: broto de planta, crescimento, jardinagem, começo",
      "maca": "Maçã: maçã, nutrição, alimentação saudável, escola",
      "tesoura": "Tesoura: tesoura, salão de beleza, cabeleireiro, corte",
      "bigode": "Bigode: bigode, barbearia, estilo masculino",
      "poste": "Poste de barbearia: poste listrado de barbearia clássica",
      "gota": "Gota: gota, pele, hidratação, skincare, estética, água",
      "brilho": "Brilhos: brilhos, estética, beleza, limpeza, magia",
      "flor": "Tulipa: flor, tulipa, floricultura, delicadeza, feminino",
      "lotus": "Flor de lótus: flor de lótus, yoga, meditação, spa, equilíbrio",
      "dente": "Dente: dente, dentista, odontologia, sorriso",
      "coracao": "Coração: coração, amor, cuidado, saúde, carinho",
      "pulso": "Batimento: linha de batimento cardíaco, saúde, medicina, fisioterapia",
      "estetoscopio": "Estetoscópio: estetoscópio, médico, clínica, consulta",
      "cruz": "Cruz da saúde: cruz da saúde, farmácia, clínica, primeiros socorros",
      "mente": "Mente: cabeça com coração, psicologia, terapia, saúde mental",
      "maos": "Mão que cuida: mão segurando um coração, cuidado, acolhimento, terapia",
      "halter": "Halter: halter, academia, musculação, treino",
      "pata": "Pata: patinha de cachorro ou gato, pet shop, veterinária",
      "osso": "Osso: ossinho de cachorro, petiscos, pet",
      "gato": "Gato: carinha de gato, pets, fofura",
      "grafico": "Gráfico em alta: gráfico subindo, crescimento, resultados, consultoria, finanças",
      "maleta": "Maleta: maleta executiva, negócios, empresas, carreira",
      "lampada": "Lâmpada: lâmpada acesa, ideias, criatividade, inovação",
      "balanca": "Balança da justiça: balança da justiça, advocacia, direito, equilíbrio",
      "calculadora": "Calculadora: calculadora, contabilidade, finanças, impostos",
      "escudo": "Escudo: escudo com check, segurança, proteção, confiança, seguros",
      "engrenagem": "Engrenagem: engrenagem, tecnologia, processos, engenharia, mecânica",
      "codigo": "Código: código </>, software, programação, tecnologia",
      "foguete": "Foguete: foguete, startup, crescimento rápido, lançamento",
      "megafone": "Megafone: megafone, marketing, divulgação, anúncios",
      "alvo": "Alvo: alvo com flecha, metas, foco, estratégia",
      "conversa": "Conversa: balões de conversa, idiomas, comunicação, atendimento",
      "livro": "Livro aberto: livro aberto, educação, cursos, leitura",
      "capelo": "Capelo: capelo de formatura, educação, cursos, formação",
      "lapis": "Lápis: lápis, escola, design, criação",
      "globo": "Globo: globo terrestre, idiomas, viagens, internacional",
      "estrela": "Estrela: estrela, destaque, qualidade, infantil, sucesso",
      "casa": "Casa: casinha, imobiliária, lar, reformas",
      "chave": "Chave: chave, imóveis, aluguel, segurança",
      "predio": "Prédio: prédio, empresa, imóveis comerciais, construtora",
      "compasso": "Compasso: compasso de desenho, arquitetura, projeto, design",
      "martelo": "Martelo: martelo, obras, reformas, marcenaria",
      "rolo": "Rolo de pintura: rolo de pintura, pintura, reformas, decoração",
      "ferramenta": "Chave inglesa: chave inglesa, oficina, conserto, manutenção",
      "carro": "Carro: carro, oficina mecânica, auto center, transporte",
      "cabide": "Cabide: cabide, moda, loja de roupas, closet",
      "camiseta": "Camiseta: camiseta, moda casual, uniformes",
      "sacola": "Sacola de compras: sacola de compras, loja, varejo, compras online",
      "loja": "Fachada de loja: fachada de loja com toldo, comércio de bairro",
      "etiqueta": "Etiqueta de preço: etiqueta de preço, promoções, ofertas",
      "diamante": "Diamante: diamante, joias, luxo, exclusividade",
      "coroa": "Coroa: coroa, realeza, premium, o melhor, barbearia",
      "camera": "Câmera: câmera fotográfica, fotografia, vídeo, ensaios",
      "aliancas": "Alianças: alianças, casamento, noivado, eventos românticos",
      "balao": "Balão de festa: balão de festa, aniversário, festas infantis, eventos",
      "presente": "Presente: caixa de presente, presentes, brindes, datas especiais",
      "cama": "Cama: cama, pousada, hotel, hospedagem, descanso",
      "sol": "Sol: sol, verão, praia, energia, alegria",
      "onda": "Onda: ondas do mar, praia, surf, pousada litorânea",
      "montanha": "Montanha: montanhas, natureza, turismo, aventura, trilhas",
      "aviao": "Avião de papel: avião de papel, viagens, envio rápido, marketing",
      "guitarra": "Guitarra: guitarra, rock, música ao vivo, bar, atitude",
      "nota": "Nota musical: notas musicais, música, aulas de música, shows",
      "raio": "Raio: raio, energia, rapidez, eletricidade, atitude",
      "relogio": "Relógio: relógio, pontualidade, rapidez, agendamento",
      "moto": "Moto de entrega: moto de entrega, delivery, motoboy"
    }
  },
  "forma": {
    "type": "choice",
    "instructions": "Qual forma de moldura combina com o símbolo do logo?",
    "criteria": {
      "circulo": "Círculo cheio: simpático, universal",
      "quadrado": "Quadrado de cantos arredondados, estilo ícone de app: moderno, digital",
      "hexagono": "Hexágono: técnico, estruturado, engenharia, colmeia",
      "escudo": "Escudo ou brasão: tradição, proteção, clube, barbearia clássica",
      "selo": "Selo circular de anel duplo, estilo carimbo: artesanal, vintage, cervejaria, café",
      "folha": "Forma orgânica de folha ou gota: natural, suave, bem-estar",
      "nenhuma": "Sem moldura: só o ícone solto, minimalista"
    }
  },
  "disp": {
    "type": "choice",
    "instructions": "Como o logo desse negócio deve ser montado?",
    "criteria": {
      "horizontal": "Símbolo à esquerda e nome ao lado: clássico e versátil",
      "empilhado": "Símbolo em cima e nome embaixo, centralizados: equilibrado, institucional",
      "emblema": "Emblema circular com o nome escrito em volta: vintage, artesanal, clube",
      "monograma": "Monograma com as iniciais dentro da forma + nome ao lado: elegante, pessoal, profissional liberal",
      "assinatura": "Nome grande como assinatura, com o símbolo pequeno de destaque: marca moderna ou autoral"
    }
  },
  "caixa": {
    "type": "choice",
    "instructions": "Como escrever o nome no logo?",
    "criteria": {
      "alta": "Nome em CAIXA ALTA espaçada: forte, clássico, imponente",
      "titulo": "Nome com Iniciais Maiúsculas: equilibrado e natural",
      "baixa": "nome em minúsculas: moderno, leve, descontraído"
    }
  },
  "estilo": {
    "type": "choice",
    "instructions": "Qual estilo de logo combina com esse negócio, com a personalidade da marca e com o que a pessoa pediu?",
    "criteria": {
      "classico": "Clássico: símbolo numa moldura simples com o nome ao lado; use só quando nenhum dos outros estilos combina claramente com a personalidade da marca",
      "palavra": "Só o nome (logotipo tipográfico) grande e elegante, com um ponto de cor: minimalista, editorial, premium, moderno",
      "bloco": "Bloco sólido de cor com o símbolo vazado e o nome forte ao lado: direto, moderno, delivery, varejo, serviços",
      "carimbo": "Carimbo ou selo circular com textura de tinta gasta, nome em arco e estrelinhas: artesanal, vintage, cervejaria, café, barbearia, rock",
      "monograma": "Monograma de luxo: iniciais dentro de um losango fino e o nome bem espaçado embaixo: sofisticado, joalheria, moda, clínica premium, advocacia",
      "bauhaus": "Composição geométrica de círculo, quarto de círculo e quadrado coloridos, estilo Bauhaus: criativo, arquitetura, escola de arte, ousado",
      "poster": "Nome empilhado em letras enormes, estilo pôster, com faixa de cor e selo redondo: energia, rock, esporte, academia, eventos",
      "manuscrito": "Nome escrito à mão em letra cursiva com sublinhado de pincel: confeitaria, café, artesanal, afetivo, romântico",
      "app": "Ícone de aplicativo com gradiente e o nome limpo ao lado: tecnologia, startup, app, fintech, digital",
      "organico": "Forma orgânica de folha ou mancha com o símbolo e o nome suave: natural, bem-estar, plantas, orgânicos, spa"
    }
  },
  "slogan": {
    "type": "choice",
    "instructions": "Qual slogan combina com esse negócio?",
    "criteria": {
      "memoria": "“Sabor que vira memória.” — Comida memorável e afetiva",
      "alma": "“Feito com alma.” — Artesanal e autêntico",
      "seu_dia": "“Do nosso jeito, pro seu dia.” — Descontraído e próximo",
      "qualidade": "“Qualidade que se sente.” — Qualidade e capricho",
      "cuidado": "“Cuidado que transforma.” — Saúde, beleza e bem-estar",
      "simples": "“Simples assim.” — Moderno, prático, minimalista",
      "paixao": "“Paixão em cada detalhe.” — Dedicação e capricho",
      "confianca": "“Confiança que gera resultado.” — Serviços profissionais e empresas",
      "crescer": "“Inteligência que faz crescer.” — Consultoria, tecnologia, B2B",
      "bem_estar": "“Bem-estar de verdade.” — Saúde, bem-estar, calma",
      "tradicao": "“Tradição e sabor desde sempre.” — Tradicional, com história",
      "volume": "“Alto volume, alto sabor.” — Rock, atitude, comida marcante",
      "arte": "“Arte, técnica e cuidado.” — Trabalho autoral e técnico",
      "sua_casa": "“Aqui é a sua casa.” — Acolhedor, familiar",
      "merece": "“Porque você merece o melhor.” — Premium e atencioso",
      "energia": "“Energia que move você.” — Esporte, energia, disposição",
      "beleza": "“Beleza que é sua.” — Beleza, autoestima",
      "aventura": "“Aprender é uma aventura.” — Educação, crianças",
      "durar": "“Feito para durar.” — Obras, oficina, produtos duráveis",
      "gostoso": "“Rápido, fácil e gostoso.” — Delivery, praticidade, comida",
      "precisao": "“Precisão em cada detalhe.” — Técnico, saúde, engenharia",
      "parceria": "“Mais que um serviço, uma parceria.” — Relacionamento com empresas",
      "natural": "“Natural como deve ser.” — Natural, orgânico, saudável",
      "classico": "“Clássico nunca sai de moda.” — Clássico, elegante, atemporal",
      "momentos": "“Pequenos detalhes, grandes momentos.” — Delicado, festas, ocasiões especiais",
      "lar": "“Onde você se sente em casa.” — Hospedagem, imóveis, acolhimento"
    }
  }
});
